### ISSUE TITLE
Could you please upload the '/Users/qiqiy/Documents/P2_WAI/Data/2.3.2.1fAreaDTA_MJs_bi.txt' file?

### ISSUE THREAD

**Issue by liamxg** [kikiyang/HPAI_Bird_world#2]
Dear @kikiyang

**Comment by kikiyang** [comment]
Hi! Sorry, I just saw your comment. This file's size exceeds GitHub's file size limit. I've just uploaded it [here](https://osf.io/upht6) to the open science framework project related to this paper.
